/*
** viki_muse.c -- see viki_muse.h for what musing is and what was rejected.
**
** This file is deliberately heavy on WHY. Every constant below was moved
** off its originally-proposed value by a measurement, and the measurements
** are the only reason to trust the new value over the old one.
*/
#include "viki_muse.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdint.h>
#include <unistd.h>

/* How many chunks to sample when estimating the corpus's own pairwise
** cosine distribution (the lower band edge). The exact median is
** O(nChunks^2) cosines -- 9.6 million on the 4382-chunk corpus measured
** below, and viki targets ~100k chunks (VIKI_DESIGN.md), where it would be
** 5 billion.
**
** Measured error against the exact median (114 / 291 / 4382-chunk corpora;
** a corpus at or below the sample size is sampled exhaustively, so it is
** exact by construction and not evidence about the estimator):
**
**   SAMPLE     114       291      4382        max error on 4382
**    100     0.4067    0.3050    0.2637           0.0084
**    200     0.3907    0.3160    0.2745           0.0024
**    400     0.3907    0.3174    0.2726           0.0005
**    800     0.3907    0.3174    0.2747           0.0026
**   exact    0.3907    0.3174    0.2721
**
** 800 is no better than 400 -- the residual is sampling noise, not bias, so
** paying more buys nothing. 400 costs 79,800 dot products (~30 ms at
** dim=384) and, on a corpus of 400 chunks or fewer, costs nothing at all
** because it becomes the exact computation.
**
** One trap here is worth naming because the first version of this code fell
** into it: 400 chunks give 79,800 PAIRS, but those pairs are not
** independent -- they are generated by 400 underlying chunks, so the
** effective sample size is 400. Do not read the pair count as precision.
**
** The second trap was a real bug, and the 291-chunk column is where it
** showed: `stride = nCorpus/want` is integer division, so 291/200 == 1 and
** the "sample" was the FIRST 200 rows of the scan rather than a spread over
** all 291. Rows of one document are adjacent in every scan order, so the
** first 200 rows are the chunks of the first handful of DOCUMENTS, which
** are far more similar to each other than the corpus is -- the estimate
** came back 0.3591 against a true 0.3174, biased HIGH, which silently
** narrows the band. Rounding the stride up fixes it. */
#define VIKI_MUSE_SAMPLE 400

/* Band edges. Both are per-run derived quantities, not tunables, but the
** two shape constants that generate them are here. See viki_muse_band(). */
#define VIKI_MUSE_SKIP_MULT   3      /* skip the seed's nearest 3*k */
#define VIKI_MUSE_WINDOW_MULT 4      /* window at least 4*k wide ... */
#define VIKI_MUSE_WINDOW_FRAC 0.05   /* ... or 5% of the corpus, whichever is more */

/* Every SQL statement that walks the corpus row-by-row carries this ORDER
** BY, and it is load-bearing rather than tidy.
**
** `viki muse --seed N` promises the same output from the same corpus on
** every machine. Without an ORDER BY, `SELECT ... FROM viki_chunk WHERE
** model_id=?` plans as a bare table scan -- measured, `EXPLAIN QUERY PLAN`
** answers `SCAN viki_chunk`, i.e. ROWID order, which is insertion order,
** which is the order `viki index` happened to walk the tree. Two peers that
** index the same content in a different directory order then disagree about
** which chunk `--seed 42` names, and the reproducibility contract is void.
** An earlier comment here asserted the scan came back in primary-key
** (content_hash) order; that was never true, and it is the assumption the
** ORDER BY replaces.
**
** Ordering by content_hash also keeps the floor sample honest: it is a
** systematic stride over a content-determined permutation of the
** DOCUMENTS, so it neither depends on nor is biased by insertion order.
** Cost measured at 4382 chunks: a TEMP B-TREE sort, well under a
** millisecond against the ~40 ms the cosine scan itself takes. */
#define VIKI_MUSE_SCAN_ORDER " ORDER BY content_hash, chunk_ix"

/* xorshift64* -- 3 lines, no libc RNG, identical stream on every platform.
** rand()/random() are explicitly NOT used: musing's whole reproducibility
** contract is that `viki muse --seed N` gives the same output on every
** machine, and rand()'s sequence is implementation-defined.
**
** The SplitMix64 finalizer in rng_seed avalanches the seed before xorshift
** ever sees it, because xorshift64 needs several iterations to mix a
** low-entropy state and its FIRST output is what picks the seed chunk.
**
** WHAT IS MEASURED, AND WHAT IS NOT, because an earlier note here claimed
** more than it could show. Shipped, 300 consecutive seeds draw 104 distinct
** seed chunks from a 114-chunk corpus against a coupon-collector expectation
** of 105.9 -- so the draw is uniform, and two seeds landing on the same
** chunk is arithmetic rather than a stuck RNG (`--seed 1` and `--seed 6`
** produce identical output on that corpus for exactly this reason).
**
** But the failure this finalizer was said to fix does NOT reproduce. Builds
** with the finalizer removed, and with the xorshift* output multiplier
** removed as well, score 27 and 35 distinct of 40 seeds on the 114-chunk
** corpus and 38 and 39 of 40 on a 334-chunk one -- noise around the same
** expectation, not the reported collapse to one chunk. The finalizer is kept
** because it costs four instructions once per process and makes the mixing
** argument obvious rather than incidental, NOT because a measurement here
** requires it. build/muse-probe.sh's B3/B4 say the same thing: they catch a
** stuck or seed-ignoring RNG and they demonstrably cannot catch an
** under-mixed one. */
static unsigned long long museRng;
static void rng_seed(unsigned long long s){
    unsigned long long z = s + 0x9E3779B97F4A7C15ULL;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    z = z ^ (z >> 31);
    museRng = z ? z : 0x9E3779B97F4A7C15ULL;
}
static unsigned long long rng_next(void){
    unsigned long long x = museRng;
    x ^= x >> 12; x ^= x << 25; x ^= x >> 27;
    museRng = x;
    return x * 2685821657736338717ULL;
}
static int rng_below(int n){ return n <= 1 ? 0 : (int)(rng_next() % (unsigned long long)n); }

static int cmp_float(const void *a, const void *b){
    float x = *(const float*)a, y = *(const float*)b;
    return x < y ? -1 : (x > y ? 1 : 0);
}

static double dot(const float *a, const float *b, int dim){
    double s = 0; int i;
    for( i = 0; i < dim; i++ ) s += (double)a[i] * (double)b[i];
    return s;
}

/* Copies a possibly-NULL sqlite3_column_text into a fixed buffer. The NULL
** case is not paranoia about our own schema (chunk_text and content_hash
** are both NOT NULL): .viki/cache.db arrives from a PEER as a `fossil uv`
** blob under D-12, so every row muse reads is untrusted input from another
** machine, and strncpy(dst, NULL, n) is a crash rather than a diagnostic. */
static void copy_text(const unsigned char *z, char *out, size_t nOut){
    if( !z ){ out[0] = '\0'; return; }
    strncpy(out, (const char*)z, nOut - 1);
    out[nOut - 1] = '\0';
}

/*
** THE BAND. This is the part that was calibrated, and the part where the
** originally-proposed numbers did not survive contact with a real corpus.
**
** The proposal was a fixed absolute band, cosine in [0.25, 0.55], chosen
** because the probe corpus's median pairwise cosine was 0.397 and the band
** straddles it -- "where real relationships live".
**
** MEASURED, on three corpora built with the pinned model:
**
**   corpus                       chunks   median cos   [0.25,0.55] holds
**   test/retrieval-corpus.sh        114       0.391      69.5% of pairs
**   this repo's own docs+src+test   291       0.317      59.7% of pairs
**   fossil's own src/ C files      4382       0.272      53.3% of pairs
**
** Two things follow, and both kill the fixed band.
**
** (1) A band centred on the median pairwise cosine is, BY DEFINITION, the
**     band a randomly chosen chunk lands in -- the median pairwise cosine
**     is what a coin-flip pair scores. It is not a coincidence that the
**     band holds most of the corpus; it is arithmetic. Measured
**     consequence on the 114-chunk corpus, muse-from-fixed-band versus
**     simply returning 5 uniformly random chunks:
**
**                          overlap w/ cosine top-5   lexical Jaccard   same-source
**       fixed [0.25,0.55]           0.016                 0.0604          0.328
**       UNIFORM RANDOM              0.028                 0.0592          0.319
**
**     They are the same distribution. The original probe's headline
**     evidence for mid-band -- "its top-5 overlaps plain cosine's top-5 by
**     only 0.02, i.e. it returns entirely different material" -- is true
**     and non-discriminating: uniform random scores 0.028 on that same
**     metric. Novelty was measured; the null hypothesis was not.
**
** (2) The constants do not transfer. 0.25-0.55 is [q0.17, q0.87] of the
**     docs corpus but [q0.42, q0.96] of the C-source corpus. Same numbers,
**     different band, because the corpus median moved 0.39 -> 0.27.
**
** So the shipped rule defines the two edges DIFFERENTLY, because they
** guard different failures:
**
**   UPPER EDGE -- rank-based, per seed. Skip the seed's nearest
**   VIKI_MUSE_SKIP_MULT*k chunks. The failure it guards is "muse just
**   returned what `viki ask` would have returned", and what it has to
**   clear is an absolute COUNT (ask's top-k), not a fraction of the
**   corpus -- so the edge is a count too. The 3x margin is because a real
**   query is not the seed's text verbatim.
**
**   LOWER EDGE -- absolute cosine, but calibrated to THIS corpus: the
**   corpus's own median pairwise cosine. That threshold has an exact
**   meaning rather than a tuned one: a chunk below it is, by definition,
**   no more related to the seed than a randomly drawn chunk is. It is the
**   arithmetic floor of "related enough to matter", and it is the guard
**   against the anti-search failure mode measured in viki_muse.h, where
**   novelty hits 1.000 and relatedness falls BELOW the random control.
**
**   WINDOW -- max(VIKI_MUSE_WINDOW_MULT*k, 5% of the corpus). The count
**   term keeps the band non-empty on a tiny corpus; the percentage term
**   keeps it from collapsing to a sliver on a large one.
**
** Measured behaviour of exactly this rule, k=5, every chunk used once as a
** seed, same-source excluded:
**
**   corpus   chunks   floor   band as % of corpus   overlap w/ ask   mean cos
**   eval        114   0.391          9.7%               0.000          0.505
**   repo        291   0.317          5.5%               0.000          0.501
**   fossil     4382   0.272          4.7%               0.000          0.517
**
** The mean cosine of what muse returns is 0.50-0.52 on all three despite
** corpus medians of 0.39 / 0.32 / 0.27. That stability IS the argument for
** the rule: it lands in the same relative place on corpora whose absolute
** distributions differ by 0.12 of cosine.
**
** And it is measurably not random, which the fixed band was not. Paired
** per-seed sign test against the uniform-random control, on lexical
** overlap with the seed: mid-band wins on 64.0% of seeds (114-chunk
** corpus, 73 of 114), 69.8% (291), 68.6% (4382) -- all three significant
** against a coin flip. Re-measured end to end with the shipped binary
** (diversity preference included) the same test gives 69.3% (79 of 114)
** and 85.8% (103 of 120 on a 334-chunk corpus).
**
** THE METRIC THAT DOES NOT WORK, recorded so it is not re-derived. Overlap
** with what search returns separates mid-band from plain cosine (0.000 by
** construction) but does NOT separate it from noise once `viki ask` is the
** yardstick instead of cosine: measured against real hybrid ask, muse
** overlaps its top-5 at 0.023 against a uniform-random control's 0.032
** (n=114) and 0.020 against 0.017 (n=334). Ask is hybrid, so its top-5
** carries BM25 hits this rank skip cannot exclude. "Low overlap with
** search" is necessary, not sufficient -- relatedness is what carries the
** claim.
**
** HONEST LIMIT, stated because it decides how much the above is worth:
** "related enough to matter" is measured here by lexical Jaccard with the
** seed, and that proxy is monotone in cosine, so it can only ever say "go
** higher". It cannot tell you whether a chunk at cos 0.52 is more USEFUL
** to muse over than one at 0.40; that is a judgement call the numbers do
** not make. What the numbers do establish is the floor and the ceiling:
** below the median the band is provably indistinguishable from noise, and
** above the skip it is provably a duplicate of `viki ask`.
*/
static void viki_muse_band(int nCorpus, int k, int *pSkip, int *pWindow){
    int skip = VIKI_MUSE_SKIP_MULT * k;
    int win  = VIKI_MUSE_WINDOW_MULT * k;
    int pct  = (int)(VIKI_MUSE_WINDOW_FRAC * (double)nCorpus + 0.999);
    if( pct > win ) win = pct;
    /* On a corpus too small to hold skip+window, shrink the SKIP first: a
    ** narrower window still returns mid-band material, but a skip that eats
    ** the whole corpus returns nothing at all. Reported as DEGRADED_SKIP. */
    if( skip + win > nCorpus - 1 ){
        skip = (nCorpus - 1) / 3;
        win  = nCorpus - 1 - skip;
        if( win < 1 ) win = 1;
    }
    *pSkip = skip; *pWindow = win;
}

/* Resolves the model_id to muse under. See viki_muse.h: emb may be NULL and
** musing must still work, because a pulled cache carries a peer's vectors
** with no local model. Picking the most-populated model_id (rather than,
** say, the first) is the right tiebreak for a cache in the normal
** multi-epoch steady state D-11 produces, where a no-model peer's
** model_id='none' rows sit alongside a real epoch's -- and the secondary
** `model_id ASC` matters for the same reason the scan order does: two
** epochs at an exactly equal count must not resolve differently on two
** machines.
**
** An EXPLICIT zModelId that matches nothing is an error rather than a
** fallback. Silently musing under a different epoch than the one the caller
** named would answer a question about epoch B with vectors from epoch A,
** and nothing in the output would say so. */
static int resolve_model(sqlite3 *db, viki_embedder *emb, const char *zWant,
                          char *out, size_t nOut, int *pCount){
    sqlite3_stmt *st;
    int rc = VIKI_MUSE_ERR_NOCORPUS;
    *pCount = 0;
    out[0] = '\0';
    if( zWant || emb ){
        const char *id = zWant ? zWant : viki_embedder_model_id(emb);
        if( sqlite3_prepare_v2(db,
                "SELECT count(*) FROM viki_chunk WHERE model_id=?1 AND embedding IS NOT NULL",
                -1, &st, NULL) == SQLITE_OK ){
            sqlite3_bind_text(st, 1, id, -1, SQLITE_STATIC);
            if( sqlite3_step(st) == SQLITE_ROW ) *pCount = sqlite3_column_int(st, 0);
            sqlite3_finalize(st);
        }
        if( *pCount > 0 ){
            copy_text((const unsigned char*)id, out, nOut);
            return 0;
        }
        if( zWant ){
            copy_text((const unsigned char*)id, out, nOut);
            return VIKI_MUSE_ERR_MODEL;
        }
        /* A model is loaded but this cache holds nothing under its epoch --
        ** fall through rather than reporting an empty corpus, so a cache
        ** pulled from a peer on a DIFFERENT epoch is still musable. */
    }
    if( sqlite3_prepare_v2(db,
            "SELECT model_id, count(*) AS n FROM viki_chunk WHERE embedding IS NOT NULL "
            "GROUP BY model_id ORDER BY n DESC, model_id ASC LIMIT 1", -1, &st, NULL) == SQLITE_OK ){
        if( sqlite3_step(st) == SQLITE_ROW ){
            copy_text(sqlite3_column_text(st, 0), out, nOut);
            *pCount = sqlite3_column_int(st, 1);
            if( out[0] ) rc = 0;
        }
        sqlite3_finalize(st);
    }
    return *pCount > 0 ? 0 : rc;
}

/* Estimates the corpus median pairwise cosine -- the lower band edge.
**
** The sample is a systematic stride over VIKI_MUSE_SCAN_ORDER, so it is a
** deterministic function of the corpus alone: two `viki muse --seed N` runs
** on the same content agree on the floor even though the seed and the picks
** are RNG-driven, and no RNG is involved here at all.
**
** Embeddings are L2-normalized by embed.c (mean-pool then normalize, the
** sentence-transformers recipe), so a plain dot product IS the cosine and
** this agrees with the ndvss_cosine_similarity_f the band uses. If that
** ever stops being true the floor and the band would silently be measured
** on two different scales.
**
** Returns the median, or VIKI_MUSE_NO_FLOOR if it could not be computed.
** The caller must flag that case -- returning "no floor" silently is
** indistinguishable, in the output, from a successful run. */
#define VIKI_MUSE_NO_FLOOR (-2.0)
static double estimate_floor(sqlite3 *db, const char *zModelId, int nCorpus, int dim){
    sqlite3_stmt *st;
    int want = nCorpus < VIKI_MUSE_SAMPLE ? nCorpus : VIKI_MUSE_SAMPLE;
    /* Round UP. Integer division here was a real bug -- see VIKI_MUSE_SAMPLE. */
    int stride = want > 0 ? (nCorpus + want - 1) / want : 1;
    float *V;
    int got = 0, row = 0, i, j;
    size_t nPair, p = 0;
    float *sims;
    double med;

    if( want < 2 ) return VIKI_MUSE_NO_FLOOR;
    if( stride < 1 ) stride = 1;
    V = malloc(sizeof(float) * (size_t)dim * (size_t)want);
    if( !V ) return VIKI_MUSE_NO_FLOOR;

    if( sqlite3_prepare_v2(db,
            "SELECT embedding FROM viki_chunk WHERE model_id=?1 AND embedding IS NOT NULL"
            VIKI_MUSE_SCAN_ORDER,
            -1, &st, NULL) != SQLITE_OK ){ free(V); return VIKI_MUSE_NO_FLOOR; }
    sqlite3_bind_text(st, 1, zModelId, -1, SQLITE_STATIC);
    while( sqlite3_step(st) == SQLITE_ROW && got < want ){
        if( row++ % stride ) continue;
        if( sqlite3_column_bytes(st, 0) != (int)(sizeof(float) * (size_t)dim) ) continue;
        memcpy(V + (size_t)got * (size_t)dim, sqlite3_column_blob(st, 0),
               sizeof(float) * (size_t)dim);
        got++;
    }
    sqlite3_finalize(st);
    if( got < 2 ){ free(V); return VIKI_MUSE_NO_FLOOR; }

    nPair = (size_t)got * (size_t)(got - 1) / 2;
    sims = malloc(sizeof(float) * nPair);
    if( !sims ){ free(V); return VIKI_MUSE_NO_FLOOR; }
    for( i = 0; i < got; i++ )
        for( j = i + 1; j < got; j++ )
            sims[p++] = (float)dot(V + (size_t)i*(size_t)dim, V + (size_t)j*(size_t)dim, dim);
    qsort(sims, nPair, sizeof(float), cmp_float);
    med = sims[nPair / 2];
    free(sims); free(V);
    return med;
}

static void fill_source(sqlite3 *db, const char *zHash, char *out, size_t nOut){
    sqlite3_stmt *st;
    strncpy(out, "(source path unknown)", nOut - 1);
    out[nOut - 1] = '\0';
    if( sqlite3_prepare_v2(db, "SELECT path FROM viki_source WHERE content_hash=?1 LIMIT 1",
            -1, &st, NULL) == SQLITE_OK ){
        sqlite3_bind_text(st, 1, zHash, -1, SQLITE_STATIC);
        if( sqlite3_step(st) == SQLITE_ROW && sqlite3_column_text(st, 0) )
            copy_text(sqlite3_column_text(st, 0), out, nOut);
        sqlite3_finalize(st);
    }
}

/* One-line excerpt for display. `viki ask` uses FTS5's snippet() centred on
** the matched terms; muse has NO query, so there is nothing to centre on
** and snippet() would be meaningless. The head of the chunk is the honest
** substitute -- and it is also what an agent needs, since a chunk's first
** line is usually its heading. Newlines are folded to spaces so a hit stays
** one line and a script can read the output positionally. */
static void excerpt_of(const char *zText, char *out, size_t nOut, int nChars){
    size_t i = 0, cap;
    if( nChars < 0 ) nChars = 0;
    cap = (size_t)nChars;
    if( cap > nOut - 1 ) cap = nOut - 1;
    while( zText[i] && i < cap ){
        unsigned char c = (unsigned char)zText[i];
        out[i] = (c == '\n' || c == '\r' || c == '\t') ? ' ' : (char)c;
        i++;
    }
    out[i] = '\0';
}

void viki_muse_defaults(viki_muse_opts *opts){
    memset(opts, 0, sizeof(*opts));
    opts->nResults = 5;
    opts->seed = 0;
    opts->bias = VIKI_MUSE_BIAS_NONE;
    opts->allowSameSource = 0;
    opts->nChars = 240;
    opts->seedIx = -1;
}

/* Picks the seed chunk. Uniform over embedded chunks by default.
**
** WHY OFFSET rather than pulling every rowid into memory: viki is designed
** for ~100k chunks and this is a single-row read; SQLite walks the ordering
** to the offset, which costs nothing next to the cosine scan that follows.
** Measured at 4382 chunks, ORDER BY + OFFSET is under a millisecond.
**
** Returns 0, or VIKI_MUSE_ERR_SEED when an explicit --from names a chunk
** this cache does not have embedded under this model_id, or
** VIKI_MUSE_ERR_INTERNAL. The distinction is the whole reason the caller
** can tell "your cache is empty" from "your hash is wrong". */
static int pick_seed(sqlite3 *db, const char *zModelId, const viki_muse_opts *opts,
                     int nCorpus, viki_muse_info *pInfo, char *outHash, int *outIx,
                     char *outText, size_t nText){
    sqlite3_stmt *st;
    int rc;
    int pickAt;
    int explicitSeed = opts->zSeedHash != NULL;

    if( explicitSeed ){
        if( sqlite3_prepare_v2(db,
                "SELECT content_hash, chunk_ix, chunk_text FROM viki_chunk "
                "WHERE model_id=?1 AND content_hash=?2 AND chunk_ix=?3 AND embedding IS NOT NULL",
                -1, &st, NULL) != SQLITE_OK ) return VIKI_MUSE_ERR_INTERNAL;
        sqlite3_bind_text(st, 1, zModelId, -1, SQLITE_STATIC);
        sqlite3_bind_text(st, 2, opts->zSeedHash, -1, SQLITE_STATIC);
        sqlite3_bind_int(st, 3, opts->seedIx < 0 ? 0 : opts->seedIx);
    }else if( opts->bias == VIKI_MUSE_BIAS_OLD ){
        /* Oldest tertile by viki_source.mtime, mtime>0 ONLY. See viki_muse.h:
        ** mtime is 0 for every virtual artifact, and sorting those first
        ** would turn "oldest" into "every wiki page, ticket and forum post"
        ** -- a bias toward a namespace wearing the costume of a bias toward
        ** age. The caller is told how much of the corpus this ignores. */
        int nUsable = 0, nDistinct = 0;
        /* COUNT is not the test; VARIANCE is. Measured on
        ** test/retrieval-corpus.sh's corpus, a count-only check reports "106
        ** of 114 chunks carry a nonzero mtime" and then orders by a column
        ** in which every one of those 106 holds the SAME value -- the corpus
        ** builder touches every file to one fixed date. "The oldest third"
        ** was then a tie-break on content_hash, i.e. an arbitrary subset
        ** presented to the reader as the oldest material. A diagnostic that
        ** cannot distinguish a real age signal from a constant is worse than
        ** no diagnostic. The same degeneracy arises for real after a fresh
        ** clone, where every file's mtime is checkout time. */
        if( sqlite3_prepare_v2(db,
                "SELECT count(*), count(DISTINCT s.mtime) FROM viki_chunk c "
                "JOIN viki_source s ON s.content_hash = c.content_hash "
                "WHERE c.model_id=?1 AND c.embedding IS NOT NULL AND s.mtime > 0",
                -1, &st, NULL) == SQLITE_OK ){
            sqlite3_bind_text(st, 1, zModelId, -1, SQLITE_STATIC);
            if( sqlite3_step(st) == SQLITE_ROW ){
                nUsable = sqlite3_column_int(st, 0);
                nDistinct = sqlite3_column_int(st, 1);
            }
            sqlite3_finalize(st);
        }
        pInfo->nAgeUsable = nUsable;
        pInfo->nAgeTotal = nCorpus;
        pInfo->nAgeDistinct = nDistinct;
        if( nUsable < 3 || nDistinct < 3 ){
            pInfo->degraded |= VIKI_MUSE_DEGRADED_NOBIAS;
            /* fall through to the uniform path below */
        }else{
            int tertile = nUsable / 3;
            if( tertile < 1 ) tertile = 1;
            pickAt = rng_below(tertile);
            if( sqlite3_prepare_v2(db,
                    "SELECT c.content_hash, c.chunk_ix, c.chunk_text FROM viki_chunk c "
                    "JOIN viki_source s ON s.content_hash = c.content_hash "
                    "WHERE c.model_id=?1 AND c.embedding IS NOT NULL AND s.mtime > 0 "
                    "GROUP BY c.content_hash, c.chunk_ix "
                    "ORDER BY min(s.mtime) ASC, c.content_hash, c.chunk_ix LIMIT 1 OFFSET ?2",
                    -1, &st, NULL) != SQLITE_OK ) return VIKI_MUSE_ERR_INTERNAL;
            sqlite3_bind_text(st, 1, zModelId, -1, SQLITE_STATIC);
            sqlite3_bind_int(st, 2, pickAt);
            goto run;
        }
    }
    if( !explicitSeed ){
        pickAt = rng_below(nCorpus);
        if( sqlite3_prepare_v2(db,
                "SELECT content_hash, chunk_ix, chunk_text FROM viki_chunk "
                "WHERE model_id=?1 AND embedding IS NOT NULL"
                VIKI_MUSE_SCAN_ORDER " LIMIT 1 OFFSET ?2",
                -1, &st, NULL) != SQLITE_OK ) return VIKI_MUSE_ERR_INTERNAL;
        sqlite3_bind_text(st, 1, zModelId, -1, SQLITE_STATIC);
        sqlite3_bind_int(st, 2, pickAt);
    }
run:
    rc = explicitSeed ? VIKI_MUSE_ERR_SEED : VIKI_MUSE_ERR_INTERNAL;
    if( sqlite3_step(st) == SQLITE_ROW && sqlite3_column_text(st, 0) ){
        copy_text(sqlite3_column_text(st, 0), outHash, 65);
        *outIx = sqlite3_column_int(st, 1);
        copy_text(sqlite3_column_text(st, 2), outText, nText);
        rc = 0;
    }
    sqlite3_finalize(st);
    return rc;
}

/* A candidate carries its TRUE rank in the seed's neighbour list. Deriving
** the rank from a position in the filtered band was a real bug: same-source
** chunks are dropped from the band but still occupy ranks, so the printed
** rank was understated by up to 6 on a measured run (rank=23 for a chunk
** whose true rank was 29). `rank` is the one number that tells an agent how
** far out a hit sits, so being quietly wrong about it is worse than not
** printing it. */
typedef struct { char hash[65]; int ix; double cos; int rank; char text[VIKI_MUSE_EXCERPT_SZ]; } museCand;

/* Has this document already supplied a result? See the diversity comment in
** viki_muse_query. Compared on content_hash rather than on the source path
** because the candidate rows already carry it -- no join, and it is exactly
** the "same document version" relation we want. */
static int doc_used(const viki_muse_result *res, int n, const char *zHash){
    int i;
    for( i = 0; i < n; i++ ) if( strcmp(res[i].hash, zHash) == 0 ) return 1;
    return 0;
}

int viki_muse_query(sqlite3 *db, const viki_muse_opts *opts, viki_embedder *emb,
                    viki_muse_result *results, int maxResults, viki_muse_info *pInfo){
    sqlite3_stmt *st;
    char seedHash[65]; int seedIx = 0;
    char *seedText;
    float *seedVec = NULL;
    int dim = 0, nCorpus = 0, nCand = 0, nCandCap = 0, nBand = 0;
    int skip, win, k, i, stratum, nOut = 0, nChars, rc;
    museCand *cand = NULL, *band = NULL;
    unsigned long long seed;

    memset(pInfo, 0, sizeof(*pInfo));
    k = opts->nResults > 0 ? opts->nResults : 5;
    if( k > maxResults ) k = maxResults;
    if( k > VIKI_MUSE_MAX_RESULTS ) k = VIKI_MUSE_MAX_RESULTS;
    pInfo->kEffective = k;
    nChars = opts->nChars < 0 ? 0 : opts->nChars;
    if( nChars > VIKI_MUSE_MAX_CHARS ) nChars = VIKI_MUSE_MAX_CHARS;

    /* A seed of 0 means "surprise me", so one is drawn from the clock+pid
    ** and REPORTED. The report is the whole point: an agent that gets an
    ** interesting muse must be able to replay it, and a seed you cannot see
    ** is a seed you cannot cite. This is why the seed is part of
    ** viki_muse_info and not a private local. */
    seed = opts->seed;
    if( seed == 0 ){
        seed = (unsigned long long)time(NULL) * 1000003ULL
             ^ ((unsigned long long)getpid() << 32)
             ^ (unsigned long long)(uintptr_t)&seed;
        if( seed == 0 ) seed = 1;
    }
    pInfo->seed = seed;
    rng_seed(seed);

    rc = resolve_model(db, emb, opts->zModelId, pInfo->modelId, sizeof(pInfo->modelId),
                       &nCorpus);
    pInfo->nCorpus = nCorpus;
    if( rc != 0 ) return rc;
    if( nCorpus < 1 ) return VIKI_MUSE_ERR_NOCORPUS;

    /* dim from the first embedding, not from emb: emb may be NULL, and a
    ** pulled cache's vectors define the geometry regardless. */
    if( sqlite3_prepare_v2(db,
            "SELECT length(embedding) FROM viki_chunk WHERE model_id=?1 "
            "AND embedding IS NOT NULL LIMIT 1", -1, &st, NULL) != SQLITE_OK )
        return VIKI_MUSE_ERR_INTERNAL;
    sqlite3_bind_text(st, 1, pInfo->modelId, -1, SQLITE_STATIC);
    if( sqlite3_step(st) == SQLITE_ROW ) dim = sqlite3_column_int(st, 0) / (int)sizeof(float);
    sqlite3_finalize(st);
    if( dim < 1 ) return VIKI_MUSE_ERR_INTERNAL;

    if( nCorpus < 2 ){
        pInfo->degraded |= VIKI_MUSE_DEGRADED_TINY_CORPUS;
        return 0;   /* nothing to relate a seed TO; not an error */
    }

    seedText = malloc(4096);
    if( !seedText ) return VIKI_MUSE_ERR_INTERNAL;
    rc = pick_seed(db, pInfo->modelId, opts, nCorpus, pInfo, seedHash, &seedIx,
                   seedText, 4096);
    if( rc != 0 ){ free(seedText); return rc; }
    memcpy(pInfo->seedHash, seedHash, sizeof(pInfo->seedHash));
    pInfo->seedIx = seedIx;
    excerpt_of(seedText, pInfo->seedExcerpt, sizeof(pInfo->seedExcerpt), nChars);
    free(seedText);
    fill_source(db, seedHash, pInfo->seedSource, sizeof(pInfo->seedSource));

    /* Seed vector. */
    if( sqlite3_prepare_v2(db,
            "SELECT embedding FROM viki_chunk WHERE model_id=?1 AND content_hash=?2 "
            "AND chunk_ix=?3", -1, &st, NULL) != SQLITE_OK ) return VIKI_MUSE_ERR_INTERNAL;
    sqlite3_bind_text(st, 1, pInfo->modelId, -1, SQLITE_STATIC);
    sqlite3_bind_text(st, 2, seedHash, -1, SQLITE_STATIC);
    sqlite3_bind_int(st, 3, seedIx);
    if( sqlite3_step(st) == SQLITE_ROW && sqlite3_column_bytes(st, 0) == (int)(sizeof(float)*(size_t)dim) ){
        seedVec = malloc(sizeof(float) * (size_t)dim);
        if( seedVec ) memcpy(seedVec, sqlite3_column_blob(st, 0), sizeof(float) * (size_t)dim);
    }
    sqlite3_finalize(st);
    if( !seedVec ) return VIKI_MUSE_ERR_INTERNAL;

    pInfo->floorSampled = estimate_floor(db, pInfo->modelId, nCorpus, dim);
    pInfo->floorCos = pInfo->floorSampled;
    if( pInfo->floorCos == VIKI_MUSE_NO_FLOOR ) pInfo->degraded |= VIKI_MUSE_DEGRADED_NOFLOOR;
    viki_muse_band(nCorpus, k, &skip, &win);
    /* Only a skip that no longer clears `viki ask`'s own top-k is worth a
    ** warning: a skip of 6 with k=5 is smaller than the 3k the rule wants,
    ** but it still guarantees muse cannot hand back what ask already did,
    ** which is the property the skip exists for. */
    if( skip < k ) pInfo->degraded |= VIKI_MUSE_DEGRADED_SKIP;
    pInfo->nSkip = skip; pInfo->nWindow = win;

    /* Pull the seed's top (skip+win) neighbours. This reuses exactly the
    ** ndvss ORDER BY that viki_ask.c's run_vector uses -- one brute-force
    ** cosine scan, SQLite's own sorter bounding the memory. It is the same
    ** cost as one `viki ask` vector leg with a larger LIMIT, which is why
    ** musing needs no new index and no schema change.
    **
    ** substr() is bound to nChars, not to a constant: a fixed
    ** substr(chunk_text,1,500) silently capped `--chars 800` at 505 bytes
    ** while reporting nothing. */
    nCandCap = skip + win + 1;   /* +1: the seed itself will be in this list */
    cand = malloc(sizeof(museCand) * (size_t)nCandCap);
    band = malloc(sizeof(museCand) * (size_t)nCandCap);
    if( !cand || !band ){ free(seedVec); free(cand); free(band); return VIKI_MUSE_ERR_INTERNAL; }

    if( sqlite3_prepare_v2(db,
            "SELECT content_hash, chunk_ix, substr(chunk_text,1,?5), "
            "       ndvss_cosine_similarity_f(?2, embedding, ?3) AS cs "
            "FROM viki_chunk WHERE model_id=?1 AND embedding IS NOT NULL "
            "ORDER BY cs DESC LIMIT ?4", -1, &st, NULL) != SQLITE_OK ){
        fprintf(stderr, "viki muse: vector query prepare failed: %s\n", sqlite3_errmsg(db));
        free(seedVec); free(cand); free(band);
        return VIKI_MUSE_ERR_INTERNAL;
    }
    sqlite3_bind_text(st, 1, pInfo->modelId, -1, SQLITE_STATIC);
    sqlite3_bind_blob(st, 2, seedVec, (int)(sizeof(float) * (size_t)dim), SQLITE_STATIC);
    sqlite3_bind_int(st, 3, dim);
    sqlite3_bind_int(st, 4, nCandCap);
    sqlite3_bind_int(st, 5, nChars + 1);
    {
        int got = 0, rank = 0;
        while( sqlite3_step(st) == SQLITE_ROW && got < nCandCap ){
            const unsigned char *h = sqlite3_column_text(st, 0);
            int ix = sqlite3_column_int(st, 1);
            if( !h ) continue;
            if( ix == seedIx && strcmp((const char*)h, seedHash) == 0 ) continue;  /* the seed itself */
            rank++;                       /* 1-based rank among NON-seed neighbours */
            copy_text(h, cand[got].hash, sizeof(cand[got].hash));
            cand[got].ix = ix;
            cand[got].cos = sqlite3_column_double(st, 3);
            cand[got].rank = rank;
            copy_text(sqlite3_column_text(st, 2), cand[got].text, sizeof(cand[got].text));
            got++;
        }
        nCand = got;
    }
    sqlite3_finalize(st);
    free(seedVec);

    /* Apply the band, then DEGRADE HONESTLY.
    **
    ** Two rules govern this block, and the first version of it broke both --
    ** found by running the prototype down a 1/2/3/5/8/12/20/40-chunk ladder
    ** rather than by reasoning about it.
    **
    ** RULE 1: a relaxation is only REPORTED when it actually changed the
    ** answer. The naive form ("band < k, so relax, so flag") flagged
    ** same-source relaxation on a corpus of one-chunk documents, where the
    ** exclusion had removed nothing and the relaxation added nothing. A
    ** degradation notice that fires when nothing degraded trains the reader
    ** to ignore degradation notices.
    **
    ** RULE 2: "the band holds fewer than k" is NOT the same fact as "a band
    ** edge is what made it small". On a 3-chunk corpus no band of any width
    ** can hold 5 results. That is a fact about the corpus and is reported as
    ** DEGRADED_THIN, separately from the edges.
    **
    ** The order of relaxation is cheapest-meaning-lost first: the
    ** same-source exclusion is a quality preference, whereas the floor is
    ** the definition of "related at all" and dropping it is exactly "muse
    ** degraded to returning random chunks". */
    {
        int nStrict;
        for( i = skip; i < nCand; i++ ){
            if( cand[i].cos < pInfo->floorCos ) break;    /* sorted desc: a break, not a filter */
            if( !opts->allowSameSource && strcmp(cand[i].hash, seedHash) == 0 ) continue;
            band[nBand++] = cand[i];
        }
        nStrict = nBand;

        if( nBand < k && !opts->allowSameSource ){
            int n2 = 0;
            for( i = skip; i < nCand; i++ ){
                if( cand[i].cos < pInfo->floorCos ) break;
                band[n2++] = cand[i];
            }
            /* The relaxed set is a superset of the strict one by construction,
            ** so n2 >= nStrict always; taking it unconditionally keeps nBand
            ** in step with what band[] now actually holds. The FLAG is NOT set
            ** here -- see the note after the cascade. */
            (void)nStrict;
            nBand = n2;
        }
        if( nBand < k ){
            int n2 = 0, prev = nBand;
            for( i = skip; i < nCand; i++ ) band[n2++] = cand[i];
            if( n2 > prev ){
                nBand = n2;
                pInfo->degraded |= VIKI_MUSE_DEGRADED_FLOOR;
                pInfo->floorCos = VIKI_MUSE_NO_FLOOR;   /* record that no floor was in force */
            }
        }
        if( nBand < 1 && nCand > 0 ){
            /* Last resort: ignore the skip. On a 2-chunk corpus the only
            ** possible answer IS the seed's nearest neighbour. */
            for( nBand = 0; nBand < nCand; nBand++ ) band[nBand] = cand[nBand];
            pInfo->degraded |= VIKI_MUSE_DEGRADED_SKIP;
            skip = 0;
            pInfo->nSkip = 0;
        }
        if( nBand < k ) pInfo->degraded |= VIKI_MUSE_DEGRADED_THIN;
    }
    pInfo->nBand = nBand;
    {   /* distinct documents in the band -- the ceiling on result diversity */
        int a, b;
        for( a = 0; a < nBand; a++ ){
            for( b = 0; b < a; b++ ) if( strcmp(band[a].hash, band[b].hash) == 0 ) break;
            if( b == a ) pInfo->nBandDocs++;
        }
    }

    /* STRATIFIED pick, with a one-document-per-result preference.
    **
    ** STRATIFYING: split the band into k equal-count strata by rank and take
    ** one from each, rather than the k highest-cosine members. The k highest
    ** members all sit against the band's upper edge, so they are about
    ** equally related to the seed AND to each other -- k restatements of one
    ** idea. Stratifying spreads the results across the band, which gives the
    ** reader a GRADIENT from "obviously connected" to "why is this here".
    ** Measured on the 114-chunk corpus, mean pairwise cosine among the 5
    ** returned chunks: 0.536 taking the top of the band, 0.498 stratified.
    ** The same comparison shows why "top of band" is wrong for a second
    ** reason: it overlaps `viki ask`'s own top-5 at 0.312 versus 0.135
    ** stratified, because the top of the band is adjacent to the bottom of
    ** what ask returns.
    **
    ** DIVERSITY: within a stratum, prefer a chunk from a document not
    ** already used. Measured on the eval corpus (114 chunks, 18 documents,
    ** every chunk once as a seed, k=5) WITHOUT this preference: the 5
    ** results averaged 2.68 distinct documents, 27.2% of seeds put 4 or more
    ** of the 5 in ONE document, and 7.0% put all five there -- because
    ** FINDINGS.md alone is 60 of the 114 chunks. "Five chunks of
    ** FINDINGS.md" is the single most visible way muse can waste an agent's
    ** attention.
    **
    ** The search deliberately stays INSIDE the stratum, wrapping from a
    ** random start. Leaving the stratum to find a fresh document would
    ** destroy the gradient stratifying exists to produce, and would trade a
    ** display preference for the ordering property that is the actual
    ** design. Where a stratum offers no fresh document the repeat is taken
    ** and REPORTED (DEGRADED_REPEATDOC) rather than hidden -- on a corpus of
    ** two documents, repeating is the only honest answer. */
    for( stratum = 0; stratum < k && nOut < maxResults; stratum++ ){
        int lo = stratum * nBand / k;
        int hi = (stratum + 1) * nBand / k;
        int at, tries, chosen = -1, span;
        if( hi <= lo ) continue;
        span = hi - lo;
        at = lo + rng_below(span);
        for( tries = 0; tries < span; tries++ ){
            int j = lo + ((at - lo) + tries) % span;
            if( !doc_used(results, nOut, band[j].hash) ){ chosen = j; break; }
        }
        if( chosen < 0 ){
            chosen = at;
            pInfo->degraded |= VIKI_MUSE_DEGRADED_REPEATDOC;
        }
        memset(&results[nOut], 0, sizeof(results[nOut]));
        memcpy(results[nOut].hash, band[chosen].hash, sizeof(results[nOut].hash));
        results[nOut].chunk_ix = band[chosen].ix;
        results[nOut].cos = band[chosen].cos;
        results[nOut].rankInSeed = band[chosen].rank;
        excerpt_of(band[chosen].text, results[nOut].excerpt, sizeof(results[nOut].excerpt),
                   nChars);
        fill_source(db, band[chosen].hash, results[nOut].source, sizeof(results[nOut].source));
        nOut++;
    }
    {   /* distinct documents actually returned */
        int a, b;
        for( a = 0; a < nOut; a++ ){
            for( b = 0; b < a; b++ ) if( strcmp(results[a].hash, results[b].hash) == 0 ) break;
            if( b == a ) pInfo->nResultDocs++;
        }
    }

    /* SAME-SOURCE is decided HERE, from what is actually being returned, and
    ** not by whichever relaxation rung happened to fire. That was a real bug,
    ** found by counting rather than by reading: MEASURED 9 of 114 seeds
    ** returned a hit from the seed's own document and 4 of those said
    ** nothing, because the floor-drop and abandon-skip rungs both rebuild
    ** band[] from ALL candidates -- same-source included -- while flagging
    ** only their own relaxation. A run that quietly hands back another chunk
    ** of the document you are already looking at, having promised not to, is
    ** the quietest possible way for muse to waste an agent's attention.
    **
    ** Deriving the flag from the RESULTS rather than from the band is also
    ** the strict reading of RULE 1: a same-source chunk that sat in the band
    ** and was never picked did not change the answer. */
    if( !opts->allowSameSource ){
        for( i = 0; i < nOut; i++ ){
            if( strcmp(results[i].hash, pInfo->seedHash) == 0 ) pInfo->nSameSrc++;
        }
        if( pInfo->nSameSrc > 0 ) pInfo->degraded |= VIKI_MUSE_DEGRADED_SAMESOURCE;
    }

    free(cand); free(band);
    return nOut;
}

/* Lists the model_ids a cache actually holds, so an unresolvable --model-id
** is answered with the answer rather than with a restatement of the
** question. */
static void print_model_ids(sqlite3 *db){
    sqlite3_stmt *st;
    if( sqlite3_prepare_v2(db,
            "SELECT model_id, count(*) FROM viki_chunk WHERE embedding IS NOT NULL "
            "GROUP BY model_id ORDER BY 2 DESC, 1 ASC", -1, &st, NULL) != SQLITE_OK ) return;
    while( sqlite3_step(st) == SQLITE_ROW ){
        fprintf(stderr, "    %-40s %d embedded chunk(s)\n",
                sqlite3_column_text(st, 0) ? (const char*)sqlite3_column_text(st, 0) : "(null)",
                sqlite3_column_int(st, 1));
    }
    sqlite3_finalize(st);
}

int viki_cmd_muse(sqlite3 *db, const viki_muse_opts *opts, viki_embedder *emb){
    viki_muse_result res[VIKI_MUSE_MAX_RESULTS];
    viki_muse_info info;
    int n, i;

    n = viki_muse_query(db, opts, emb, res, VIKI_MUSE_MAX_RESULTS, &info);

    /* Each failure gets its OWN sentence. The first version answered every
    ** one of them with "no embedded chunks in this cache", which for a bad
    ** --from hash is a false statement about a cache holding 114 embedded
    ** chunks and sends the reader off to re-run `viki index`. */
    if( n == VIKI_MUSE_ERR_NOCORPUS ){
        fprintf(stderr,
            "viki muse: no embedded chunks in this cache -- musing is a vector-only\n"
            "  mode and has no BM25 fallback (there is no keyword analogue of \"in the\n"
            "  middle of the similarity distribution\"). Run `viki index` with a model\n"
            "  present, or `viki cache pull` a cache a peer already embedded (D-11).\n");
        return 1;
    }
    if( n == VIKI_MUSE_ERR_SEED ){
        fprintf(stderr,
            "viki muse: --from %s#%d is not an embedded chunk of this cache under\n"
            "  model_id=%s (the cache does hold %d embedded chunk(s), so this is a\n"
            "  wrong identity, not an empty index). Copy the `<content_hash>#<chunk_ix>`\n"
            "  field verbatim from a `viki ask` or `viki muse` hit -- the hash is the\n"
            "  full 64 hex digits and is not matched by prefix.\n",
            opts->zSeedHash ? opts->zSeedHash : "(null)",
            opts->seedIx < 0 ? 0 : opts->seedIx, info.modelId, info.nCorpus);
        return 1;
    }
    if( n == VIKI_MUSE_ERR_MODEL ){
        fprintf(stderr,
            "viki muse: no embedded chunks under model_id=%s. This cache holds:\n",
            info.modelId);
        print_model_ids(db);
        return 1;
    }
    if( n < 0 ){
        fprintf(stderr, "viki muse: internal error reading the cache: %s\n", sqlite3_errmsg(db));
        return 1;
    }

    /* The run header is stderr, the hits are stdout -- same split `viki ask`
    ** uses, so `viki muse | ...` pipes only the results. Everything needed
    ** to reproduce or explain the run is here, because a muse an agent
    ** cannot replay is an anecdote rather than a memory. */
    fprintf(stderr,
        "viki muse: seed=%llu  model_id=%s  corpus=%d chunk(s)\n",
        (unsigned long long)info.seed, info.modelId, info.nCorpus);
    /* TWO DIFFERENT FACTS, and they used to share one field. floorSampled is
    ** a property of the CORPUS -- the median pairwise cosine -- and is the
    ** same for every seed. floorCos is the EFFECTIVE floor, which the
    ** degradation cascade overwrites with a sentinel when a thin band forces
    ** it to be dropped. Printing only the effective value meant a run that
    ** dropped the floor reported nothing about the corpus at all, so two
    ** seeds over one corpus produced band lines that disagreed about a number
    ** that cannot vary. build/muse-probe.sh B7 asserts exactly that
    ** invariant, and caught this. Report both: what the floor IS, and whether
    ** it was applied. */
    if( info.floorSampled == VIKI_MUSE_NO_FLOOR ){
        /* The estimator itself could not sample -- a genuinely floorless
        ** corpus, not a thin draw. Never print the -2 sentinel as if it were
        ** a measurement. */
        fprintf(stderr,
            "  band: skip the seed's nearest %d, window %d, no floor could be estimated\n"
            "  %d chunk(s) in band, from %d distinct document(s)\n",
            info.nSkip, info.nWindow, info.nBand, info.nBandDocs);
    }else{
        fprintf(stderr,
            "  band: skip the seed's nearest %d, window %d, floor cos>=%.4f "
            "(corpus median pairwise cosine)%s\n"
            "  %d chunk(s) in band, from %d distinct document(s)\n",
            info.nSkip, info.nWindow, info.floorSampled,
            info.floorCos == VIKI_MUSE_NO_FLOOR
                ? " -- NOT IN FORCE this draw, band too thin" : "",
            info.nBand, info.nBandDocs);
    }
    if( opts->nResults != info.kEffective ){
        fprintf(stderr, "  NOTE: --k %d is out of range; using %d (1..%d)\n",
                opts->nResults, info.kEffective, VIKI_MUSE_MAX_RESULTS);
    }
    if( opts->nChars > VIKI_MUSE_MAX_CHARS ){
        fprintf(stderr, "  NOTE: --chars %d capped at %d; fetch the whole chunk by its "
                        "<content_hash>#<chunk_ix>\n", opts->nChars, VIKI_MUSE_MAX_CHARS);
    }

    if( info.degraded ){
        fprintf(stderr, "  DEGRADED:");
        if( info.degraded & VIKI_MUSE_DEGRADED_TINY_CORPUS )
            fprintf(stderr, " corpus too small to relate anything to (need >=2 chunks);");
        if( info.degraded & VIKI_MUSE_DEGRADED_NOFLOOR )
            fprintf(stderr, " the corpus median pairwise cosine could not be computed, "
                            "so NO floor was applied -- results may be no more related to "
                            "the seed than a random chunk;");
        if( info.degraded & VIKI_MUSE_DEGRADED_SAMESOURCE )
            fprintf(stderr, " %d of %d result(s) come from the seed's OWN document -- the band "
                            "was too thin to exclude it;", info.nSameSrc, n);
        if( info.degraded & VIKI_MUSE_DEGRADED_FLOOR )
            fprintf(stderr, " band too thin, so the cos>=%.4f floor was DROPPED -- "
                            "results below it are no more related to the seed than a "
                            "random chunk;", info.floorSampled);
        if( info.degraded & VIKI_MUSE_DEGRADED_SKIP )
            fprintf(stderr, " corpus too small to skip the seed's nearest neighbours at all, "
                            "so results DO overlap what `viki ask` would return;");
        if( info.degraded & VIKI_MUSE_DEGRADED_REPEATDOC ){
            /* Two different facts, and only one of them is the reader's to
            ** act on. If the band cannot hold k documents no setting helps;
            ** if it can, the repeat is a stratum that happened to offer only
            ** documents already used, which is a much weaker complaint. */
            if( info.nBandDocs < info.kEffective )
                fprintf(stderr, " the band holds only %d distinct document(s), so at most "
                                "%d of the %d result(s) can be from different documents;",
                        info.nBandDocs, info.nBandDocs, info.kEffective);
            else
                fprintf(stderr, " %d of %d result(s) repeat a document (the band spans %d) -- "
                                "a stratum offered no unused document, and leaving the stratum "
                                "to find one would break the near-to-far gradient;",
                        info.kEffective - info.nResultDocs, info.kEffective, info.nBandDocs);
        }
        if( info.degraded & VIKI_MUSE_DEGRADED_THIN )
            fprintf(stderr, " only %d chunk(s) can be returned -- the corpus is too small "
                            "for %d, not the band;", info.nBand, info.kEffective);
        if( info.degraded & VIKI_MUSE_DEGRADED_NOBIAS )
            fprintf(stderr, " --bias old ignored: %d of %d chunks have a nonzero "
                            "viki_source.mtime and they carry only %d distinct value(s) "
                            "-- no age signal (virtual artifacts have none, and a fresh "
                            "clone gives every file the same one);",
                    info.nAgeUsable, info.nAgeTotal, info.nAgeDistinct);
        fprintf(stderr, "\n");
    }
    if( opts->bias == VIKI_MUSE_BIAS_OLD && !(info.degraded & VIKI_MUSE_DEGRADED_NOBIAS) ){
        fprintf(stderr, "  --bias old: drew from the oldest third of the %d of %d chunk(s) "
                        "carrying a nonzero mtime (%d distinct value(s))\n",
                info.nAgeUsable, info.nAgeTotal, info.nAgeDistinct);
    }
    fprintf(stderr, "\n");

    if( n == 0 ){
        fprintf(stderr, "(nothing to muse over)\n");
        return 1;
    }

    /* SEED line, then hits. An agent reading this needs to know what the
    ** results are relative TO, or the cosines are meaningless. Same
    ** `<content_hash>#<chunk_ix>  <source>` identity `viki ask` prints and
    ** `/api/chunk?hash=&ix=` accepts, so a muse hit can be fetched in full
    ** without a translation step -- and so an agent can re-muse FROM a hit
    ** with `--from <hash>#<ix>`, which is how a chain of association gets
    ** followed. Fixed-width fields first, ragged source last. */
    printf("seed  %s#%d  %s\n    %s\n\n",
           info.seedHash, info.seedIx, info.seedSource, info.seedExcerpt);
    for( i = 0; i < n; i++ ){
        printf("[%d] cos=%.4f rank=%d  %s#%d  %s\n    %s\n\n",
               i + 1, res[i].cos, res[i].rankInSeed, res[i].hash, res[i].chunk_ix,
               res[i].source, res[i].excerpt);
    }
    return 0;
}
